FROM ubuntu
MAINTAINER Vincent Mizoules

RUN apt-get update && apt-get install -y \
        g++ \
        build-essential \
        make \
        libzzip-dev \
    && echo "Install done."

WORKDIR /var/www

CMD [""]